/*
====================================================================
Magnitude Analysis
====================================================================
	-analysis of measure by dimensions
	- Quantify the data and group by specific dimensions.
	- Understinding distribution of data across categories.
SQL functions used:
	- aggregation functions : SUM, COUNT, AVG,MIN, MAX
	- GROUP BY, ORDER BY
*/

-- Find total customers by countries.
select country, count(*) as no_of_customers
from gold.dim_customers
group by country
order by no_of_customers desc;

--Find total customers by gender.
select gender, count(*) no_of_customers
from gold.dim_customers
group by gender
order by no_of_customers desc ;

--Find total products by category.
select category, count(*) as no_of_products
from gold.dim_products
group by category
order by no_of_products desc;

--Find the average costs in each category.
select category, avg(cost) as average_cost
from gold.dim_products
group by category
order by average_cost desc;

--Find total revenue generated by each category.
select 
	p.category,
	sum(s.sales_amount) as total_revenue
from gold.fact_sales s
left join gold.dim_products p
ON p.product_key = s.product_key
group by p.category
order by total_revenue desc
;

--Find total revenue generated by each customer.
select 
	c.customer_key,
	c.first_name,
	c.last_name,
	sum(s.sales_amount) as total_revenue
from gold.fact_sales s
left join gold.dim_customers c
ON c.customer_key = s.customer_key
group by c.customer_key,
	c.first_name,
	c.last_name
order by total_revenue desc;

--Find the distribution of sold items across countries.
select 
	c.country,
	sum(s.quantity) as item_sold
from gold.fact_sales s
left join gold.dim_customers c
ON c.customer_key = s.customer_key
group by c.country
order by item_sold desc;